# Generated by Django 5.2.7 on 2025-10-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_module_slug_alter_module_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
