# Generated by Django 5.2.7 on 2025-10-21 00:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_alter_module_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('duration', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQuantity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Display order within the module', null=True),
        ),
        migrations.AddConstraint(
            model_name='questions',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_order_per_module'),
        ),
    ]
