# Generated by Django 5.2.7 on 2025-10-21 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_customtime_questionquantity_alter_questions_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionModulesPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pair_number', models.PositiveIntegerField(help_text='1, 2, or 3 for Optional 1, 2, 3')),
                ('module_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_as_module_a', to='module.module')),
                ('module_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_as_module_b', to='module.module')),
            ],
        ),
    ]
