# Generated by Django 5.2.7 on 2025-11-06 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_optionmodulespair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('total_questions', models.PositiveIntegerField()),
                ('time_limit', models.PositiveIntegerField(help_text='Minutes')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('xp_gained', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttendQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('selected_answer', models.CharField(blank=True, choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], max_length=7, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='optionmodulespair',
            name='pair_number',
            field=models.PositiveIntegerField(help_text='Must be unique — 1, 2, or 3 for Optional 1, 2, 3', unique=True),
        ),
        migrations.AddConstraint(
            model_name='optionmodulespair',
            constraint=models.UniqueConstraint(fields=('module_a', 'module_b'), name='unique_module_pair'),
        ),
        migrations.AddField(
            model_name='quizattend',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attends', to='module.module'),
        ),
        migrations.AddField(
            model_name='quizattend',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizattendquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.questions'),
        ),
        migrations.AddField(
            model_name='quizattendquestion',
            name='quiz_attend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_questions', to='module.quizattend'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattendquestion',
            unique_together={('quiz_attend', 'question')},
        ),
    ]
