# Generated by Django 5.2.7 on 2025-11-06 21:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_quizattend_quizattendquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattend',
            name='correct_count',
        ),
        migrations.RemoveField(
            model_name='quizattend',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='quizattend',
            name='incorrect_count',
        ),
        migrations.RemoveField(
            model_name='quizattend',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='quizattend',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='quizattend',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='quizattend',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattend',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='quizattend',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quizattend',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module'),
        ),
        migrations.AlterField(
            model_name='quizattend',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='QuizAttendQuestion',
        ),
    ]
