# Generated by Django 5.2.7 on 2025-11-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_remove_quizattend_correct_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattend',
            name='attempted_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
