# Generated by Django 5.2.7 on 2025-11-25 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0008_quizattend_attempted_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pair_number', models.PositiveIntegerField()),
                ('selected_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'pair_number')},
            },
        ),
    ]
