# Generated by Django 5.2.7 on 2025-11-25 21:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0008_quizattend_attempted_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynopticModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modules', models.ManyToManyField(related_name='synoptic_module', to='module.module')),
            ],
        ),
    ]
